apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-1
  namespace: nagp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: nagp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
      namespace: nagp
    spec:
      containers:
      - name: postgres
        image: 052758471237.dkr.ecr.ap-south-1.amazonaws.com/postgres-custom:latest
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pgsql-secret
                key: password
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgresv2
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc-1
      restartPolicy: Always  
  strategy:
    type: Recreate    
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: nagp
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
