name: 5. Deployment EKS Cluster

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  RELEASE_REVISION: "pr-${{ github.event.pull_request.number }}-${{github.ref_name}}"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
  KUBE_NAMESPACE: nagp  

jobs:
  build:

    runs-on: ubuntu-latest
    environment: 
      name: Production
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Create tag artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{github.ref_name}}
        path: Release
    
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
           
    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.25.0' # default is latest stable
      id: install
      
    - name: Update kube config
      run: aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name nagp-k8s-devops-assessment --kubeconfig $HOME/.kube/config
      
    #- name: Configure kubectl
    #  run: |
    #      echo "${{ env.KUBE_CONFIG_DATA }}" > $HOME/.kube/config       
    
    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s
